services:
  ecommerce-db:
    image: postgres:16-alpine
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ecommerce
    ports:
      - "127.0.0.1:5432:5432"  # solo accesible desde localhost
    volumes:
      - ecommerce-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  ecommerce-db-data:

